application:
  actions: actions
  runtimeManifest:
    packages:
      kotak-bff:
        license: Apache-2.0
        actions:
          rates:
            function: actions/rates/index.js
            web: 'yes'
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: info
            annotations:
              require-adobe-auth: false
              final: true
